### ISSUE TITLE
I cannot see my application in web-console when using Safari

### ISSUE THREAD

**Issue by jonaspetersorensen** [equinor/radix-platform#103] opened 2019-03-01 11:11 UTC
Thanks for taking the time to report an issue or feature request.

If applicable, please provide the following information:

Application name in Radix: autorepgen

Application component: n/a

Cluster: beta-9

Reporting on behalf of Geir-Tore Lindsve (autorepgen dev).

When he is using Safari to browse the web-console, then the web-console will show an empty list of applications.
When he is using Chrome everything works as expected (he can see his application in the list).

When inspecting the requests in web developer tool he can see that the "application" request returns 
```
[Error] Error subscribing to  – "/applications" – "AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent i…"
    (anonym funksjon) (main.11ea0813.chunk.js:1:31893)
    k (3.9a5f72b7.chunk.js:1:599383)
    (anonym funksjon) (3.9a5f72b7.chunk.js:1:599168)
    R (3.9a5f72b7.chunk.js:1:175138)
    w (3.9a5f72b7.chunk.js:1:176117)
    promiseReactionJob
```

**Comment by nemzes** [comment] 2019-05-03 10:22
Closing this due to inability to reproduce.

**Closed by nemzes** 2019-05-03 10:22 UTC
