### ISSUE TITLE
Allow re-generating Radix deploy keys

### ISSUE THREAD

**Issue by trylle** [equinor/radix-platform#412] opened 2021-03-02 08:33 UTC
**Is your feature request related to a problem? Please describe.**
To be compliant with WR1211, we need to be able to create new deploy keys every year. The Radix console does not offer this functionality and uses the same key all the time.

See https://equinor.slack.com/archives/CBKM6N2JY/p1614579636016500

**Describe the solution you'd like**
Some way to regenerate the deploy key - a button?

**Comment by emirgens** [comment] 2021-03-02 08:40
Duplicate of #413

**Closed by emirgens** 2021-03-02 08:40 UTC
Labels: enhancement
