### ISSUE TITLE
Parsing errors on radix config file

### ISSUE THREAD

**Issue by john-haugland** [equinor/radix-platform#395] opened 2021-01-11 17:30 UTC
**Is your feature request related to a problem? Please describe.**
When there is a spell error or missing keyword in the radix config file, it would be good to have feedback in order to correct the syntax. 

**Describe the solution you'd like**
When deploying a radix config, it would be good to have error reports on parts of the config that Radix is not able to use. 

**Describe alternatives you've considered**

**Additional context**

**Comment by emirgens** [comment] 2021-03-08 11:43
Duplicate of #265 
These are probably almost the same thing, I'll close this.

**Closed by emirgens** 2021-03-08 11:43 UTC
Labels: enhancement
